"""Initial Migration

Revision ID: 14327040e4b6
Revises: 
Create Date: 2024-12-09 14:00:34.524232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14327040e4b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('cellphone', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('main_operation_geocode', sa.String(length=50), nullable=True),
    sa.Column('average_review_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_user_id', sa.Integer(), nullable=False),
    sa.Column('sending_company_user_id', sa.Integer(), nullable=False),
    sa.Column('receiving_company_user_id', sa.Integer(), nullable=False),
    sa.Column('sender_geocode', sa.String(length=50), nullable=True),
    sa.Column('receiver_geocode', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_image', sa.String(length=255), nullable=True),
    sa.Column('product_details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['courier_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['receiving_company_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sending_company_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('g_uuid', sa.String(length=255), nullable=True),
    sa.Column('last_logged_in', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('company_score', sa.Float(), nullable=False),
    sa.Column('courier_score', sa.Float(), nullable=False),
    sa.Column('company_score_comment', sa.String(length=255), nullable=True),
    sa.Column('courier_score_comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_reviews')
    op.drop_table('delivery_messages')
    op.drop_table('sessions')
    op.drop_table('deliveries')
    op.drop_table('users')
    # ### end Alembic commands ###
