"""Fix types

Revision ID: a022d0e00921
Revises: 14327040e4b6
Create Date: 2024-12-10 08:56:01.897700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a022d0e00921'
down_revision = '14327040e4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.alter_column('sender_geocode',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('receiver_geocode',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('product_image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('Pending', 'Assigned', 'OnCourse', 'Failed', 'Completed', name='deliverystatus'),
               existing_nullable=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_position_geocode', sa.JSON(), nullable=False))
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('g_uuid',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['g_uuid'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('Courier', 'Company', 'ServiceManager', name='userrole'),
               existing_nullable=False)
        batch_op.alter_column('main_operation_geocode',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('main_operation_geocode',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.Enum('Courier', 'Company', 'ServiceManager', name='userrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('g_uuid',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('device_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('last_position_geocode')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Pending', 'Assigned', 'OnCourse', 'Failed', 'Completed', name='deliverystatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('product_image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('receiver_geocode',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('sender_geocode',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
